import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.PREVIEW_URL||'http://127.0.0.1:4174/';
 await page.goto(`${base}?core=2#lesson/c2-windows-editions`);
 const nav=page.getByRole('navigation',{name:'Study navigation'});
 await nav.getByRole('link',{name:'Next lesson'}).click();
 await page.waitForURL('**#lesson/c2-windows-settings');
 await page.keyboard.press('Alt+ArrowLeft');
 await page.waitForURL('**#lesson/c2-windows-editions');
 await page.keyboard.press('ArrowRight');
 await page.getByRole('button',{name:'Visualize',exact:true}).first().waitFor();
 assert.equal(await page.locator('.section-tab.active').innerText(),'Visualize');
 await page.locator('#lesson-notes').fill('Keep my notes');
 await page.keyboard.press('Alt+ArrowRight');
 assert.ok(page.url().endsWith('c2-windows-editions'),'Editing notes must not trigger navigation');
 await page.locator('#main').focus();
 await page.keyboard.press('Alt+ArrowRight');
 await page.waitForURL('**#lesson/c2-windows-settings');
 await page.getByRole('button',{name:'Knowledge check',exact:true}).first().click();
 await nav.getByRole('button',{name:'Next lesson'}).click();
 await page.waitForURL('**#lesson/c2-client-networking');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('core-two-mentor-v1')).completed.length),0,'Navigation does not mark lessons complete');
 await page.setViewportSize({width:390,height:844});
 await page.reload();
 await page.locator('.learning-panel').waitFor();
 await page.evaluate(()=>scrollTo(0,400));
 const bounds=await nav.boundingBox();
 const menu=await page.locator('.mobile-nav').boundingBox();
 assert.ok(bounds.y>=0&&bounds.y+bounds.height<=menu.y,'Phone controls stay above the menu');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');
 await nav.getByRole('link',{name:'Previous lesson'}).click();
 await page.waitForURL('**#lesson/c2-windows-settings');
 await page.screenshot({path:'audit/navigation-mobile.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: mouse, keyboard, note editing, ungated lesson navigation, mobile placement, and completion integrity.');
}finally{await browser.close();}
