import {lessons} from './data.js';
// Each row adds a concept check and an application check to the original scenario.
const extras={
 foundations:[['Which is software?','An operating system','A keyboard','A CPU','An operating system contains instructions. Keyboards and CPUs are physical hardware.'],['Where does a saved document persist after shutdown?','Nonvolatile storage','Ordinary RAM only','The display panel','Storage preserves saved data without power. Ordinary RAM is volatile; a display presents output.']],
 'ram-storage':[['Which is normally volatile?','RAM','An SSD','A hard disk','RAM requires power to retain active data. SSDs and hard disks retain saved files without power.'],['A drive is nearly full of saved videos. What addresses that capacity problem?','Archive or move files to suitable storage','Add more RAM alone','Increase display resolution','The constraint is storage space. More RAM does not make the drive larger, and display resolution is unrelated.']],
 'router-switch':[['What does a typical Layer 2 switch use to forward known unicast frames?','A MAC address table','A list of DNS names','CPU temperatures','MAC address learning maps destinations to ports. DNS resolves names; temperature is unrelated to forwarding.'],['What connects wireless clients to a local network?','An access point','A passive patch panel alone','A power supply','An access point bridges wireless clients into the LAN. A patch panel organizes cabling; a PSU provides power.']],
 dns:[['Which DNS record provides an IPv6 address?','AAAA','A','MX','AAAA maps a name to IPv6. A maps to IPv4; MX identifies mail exchangers.'],['Which command directly investigates a DNS lookup?','nslookup','A disk format command','A printer test page','nslookup queries DNS. Formatting a drive is destructive and unrelated; a test page checks printing.']],
 dhcp:[['Which is the IPv4 DHCP server port?','UDP 67','UDP 68','TCP 443','The server listens on UDP 67; clients use UDP 68. TCP 443 conventionally serves HTTPS.'],['Which DHCP feature allocates a consistent address to a particular client?','Reservation','Exclusion alone','A larger monitor','A reservation associates a client with an address. An exclusion only removes addresses from the allocation pool; a monitor has no DHCP role.']],
 'tcp-udp':[['Does TCP encrypt application data by itself?','No','Always','Only when using port 80','TCP provides transport reliability, not encryption. Neither TCP use nor port 80 supplies confidentiality.'],['Why might an application choose UDP for live media?','It can avoid waiting for transport retransmissions','It guarantees no packets are lost','It encrypts all audio automatically','UDP permits application-specific handling of delay and loss. It guarantees neither delivery nor encryption.']],
 ports:[['Which service conventionally uses TCP 445?','SMB','SSH','DNS','SMB uses TCP 445 for file and printer sharing. SSH uses 22; DNS uses 53.'],['Which port pair belongs to IPv4 DHCP?','67/68','20/21','137–139','67/68 is DHCP. 20/21 belongs to FTP; 137–139 relates to NetBIOS services.']],
 ipv4:[['How many bits are in an IPv4 address?','32','128','48','IPv4 has 32 bits. IPv6 has 128; an Ethernet MAC address is conventionally 48 bits.'],['A workstation must send to a different subnet. Which setting usually identifies its next hop?','Default gateway','Screen brightness','Keyboard layout','The gateway provides the route outside the local subnet. Display and input settings do not route packets.']],
 wifi:[['Which statement about 6 GHz Wi-Fi is accurate?','Both the access point and client need compatible support','Every 2.4 GHz client can use it','It always penetrates walls better than 2.4 GHz','6 GHz requires compatible radios and standards. Legacy clients cannot gain it through an SSID change, and higher frequency is not a wall-penetration guarantee.'],['What should you compare when a laptop is slow only far from the access point?','Performance closer to the access point','Printer ink levels','The desktop power supply','A distance comparison helps isolate signal and obstruction effects. Ink and a separate desktop PSU are unrelated.']],
 motherboard:[['What is UEFI used for?','Firmware-level startup and configuration','Keeping all saved documents','Replacing the CPU physically','UEFI initializes and configures startup behavior. It is neither user file storage nor a physical processor replacement.'],['A board fits the CPU but not the case. Which factor was overlooked?','Motherboard form factor and case support','DNS server selection','User account name','Board dimensions and mounting must match the case. Network and account settings do not change the physical fit.']],
 cpu:[['What is thermal throttling?','Reducing performance to manage heat','Adding permanent storage','Resolving a domain name','Throttling reduces performance under thermal constraints. Storage capacity and DNS are different functions.'],['Why can two processors at the same GHz perform differently?','Architecture, cores, cache, and workload differ','GHz guarantees equal performance','Screen size sets CPU throughput','Clock speed is only one factor. Architecture and workload matter; display dimensions do not establish CPU throughput.']],
 ram:[['Which memory feature can correct certain memory errors?','ECC with a supporting platform','A larger SSD alone','A higher monitor refresh rate','Error-correcting code memory works with platform support. Storage capacity and display refresh do not provide memory error correction.'],['Where should you look for the correct dual-channel slot placement?','The motherboard service manual','The wallpaper settings','The router SSID label','The board manual specifies slot population. Cosmetic settings and wireless identifiers do not describe RAM channels.']],
 storage:[['What does M.2 primarily describe?','A form factor','A guarantee of NVMe support','A backup method','M.2 describes physical format. Protocol support depends on the device and slot; it does not supply backups.'],['Does RAID replace an independent backup?','No','Yes, for every RAID level','Yes, if the disks are SSDs','RAID does not protect against every deletion, corruption, or site failure. Disk technology does not remove the need for backups.']],
 power:[['What does a PC power supply convert?','AC input to DC outputs','DNS names to addresses','Documents to printed pages','A PSU supplies DC power from AC input. DNS resolves names; printers produce pages.'],['What is the safe approach to a failed PSU enclosure?','Replace the unit using approved procedures','Open it to inspect charged capacitors','Probe inside while it is powered','Internal stored charge can be hazardous. Unit replacement avoids unsafe internal probing or repairs.']],
 printers:[['Which printer type commonly supports multipart forms?','Impact','Laser','Direct thermal','Impact pins strike through ribbon and layered forms. Laser and direct thermal do not mechanically imprint the underlying sheets.'],['An inkjet produces streaks from clogged nozzles. Which maintenance is relevant?','Run the approved printhead cleaning process','Replace a laser fuser','Change the Wi-Fi SSID','Inkjet nozzle cleaning addresses this symptom. A laser fuser is not an inkjet component, and an SSID change does not clean nozzles.']],
 vm:[['A VM runs through virtualization software on a desktop OS. Which hypervisor type is this?','Type 2','Type 1','A DNS record type','Type 2 operates on a host OS. Type 1 runs directly on hardware; DNS record types describe name-service data.'],['Why should you avoid allocating all host RAM to one VM?','The host and other workloads still need memory','VMs never need memory','It automatically deletes the host OS','Over-allocation can cause memory pressure. VMs do need memory; allocation alone does not delete the operating system.']],
 cloud:[['Which model delivers a finished application to users?','SaaS','IaaS','A local hypervisor alone','SaaS provides the application. IaaS provides infrastructure; a hypervisor alone does not deliver that cloud service model.'],['What is cloud elasticity?','Adjusting resources as demand changes','Always buying a larger physical monitor','Never measuring usage','Elasticity matches capacity to demand. Monitor purchasing is unrelated, and cloud usage may be metered.']],
 method:[['Is memorizing the named methodology a formal V15 exam objective?','No; it is supporting practice','Yes, a separately weighted sixth domain','Yes, the only troubleshooting skill','The official objectives explicitly exclude the named methodology as a formal objective. There are five domains, and practical troubleshooting remains important.'],['After applying a fix, what should you do?','Verify full functionality and document the outcome','Assume success without testing','Delete the incident record','Verification checks that the fix worked; documentation preserves useful evidence. Assumption and deleting records lose that assurance.']],
 'no-internet':[['Does a failed ping prove the target is down?','No; ICMP may be filtered','Yes, in every case','Only if the screen is dim','Filtering can prevent ping replies even when a service works. Display brightness is irrelevant, so use additional evidence.'],['All devices lose internet at the same time. What should receive attention?','Shared gateway and upstream connectivity','Every keyboard cable first','One local printer cartridge','Shared symptoms suggest a common path. Keyboard cables and printer consumables do not normally provide internet routing.']],
 'no-power':[['Fans run but the screen is blank. Is this necessarily no power?','No; investigate the display and POST stage','Yes; fans never indicate power','It proves DNS failed','Fan activity shows some power, though not full PSU health. A blank screen can have multiple causes and does not diagnose DNS.'],['A PC emits a burning smell. What takes priority?','Stop use and safely disconnect power if possible','Continue stress-testing it','Reinstall the browser','A burning smell calls for safe shutdown and service. More load can worsen a fault; a browser install cannot address it.']],
 laptop:[['Why check a laptop service manual before a RAM upgrade?','RAM may be soldered or have model-specific limits','Every laptop uses desktop DIMMs','The manual changes the RAM generation','The manual identifies serviceability and limits. Desktop modules are not universal, and documentation does not alter hardware generation.'],['What matters when reinstalling a laptop wireless card?','Correct antenna connector placement and routing','Matching the desktop wallpaper','Adding printer paper','Antenna placement affects radio operation, and connectors are delicate. Wallpaper and printer paper do not restore the RF path.']],
 mobile:[['What does a mobile hotspot normally do?','Share a data connection with other devices','Add RAM to nearby laptops','Increase headset battery capacity','A hotspot shares connectivity. It does not provide additional memory or change accessory battery capacity.'],['Does a USB-C connector guarantee video output?','No; device, port, and cable capabilities matter','Yes; all USB-C ports have identical features','Only the cable color matters','USB-C describes a connector. Supported functions vary, and cable color is not a reliable specification.']]
};
export function checksFor(l){return [l,...(l.checks ? l.checks.slice(1) : extras[l.id]).map((r,i)=>({...l,number:l.number+i+1,question:r[0],options:r.slice(1,4),explanation:r[4]}))].map((q,checkSlot)=>({...q,checkSlot}));}
export const questionCount=lessons.reduce((n,l)=>n+checksFor(l).length,0);
