// Original hardware instruction with worked exercises and explanatory checks.
export const componentLessons = [
{
id:'cooling',title:'Cooling: move heat out of the computer',domain:3,objective:'3.5 / 5.1',minutes:24,
big:'Cooling transfers heat from components into the surrounding air; every part of that path must work.',
taglish:'Hindi sapat na umiikot ang fan. Dapat tama ang contact ng cooler, may airflow, at walang bara ang vents. Thermal paste fills tiny gaps; hindi siya kapalit ng heatsink.',
analogy:'Moving heat is like removing water through connected pipes. A blockage anywhere can limit the entire system, even when the pump runs.',
exam:'Cooling can use heatsinks, fans, thermal interface material, and liquid-cooling components. Thermal throttling reduces performance to manage temperature. Overheating may cause slowdowns or shutdowns, but those symptoms can have other causes.',
tech:'A computer runs normally at idle but slows under sustained load. Compare temperatures, clock behavior, and fan operation with manufacturer guidance before choosing a repair.',
flow:['Component heat','Thermal interface','Heatsink or liquid loop','Air outside the case'],
goals:['Explain each stage in the heat path','Compare air and liquid cooling','Investigate heat-related symptoms without disabling protection'],
terms:[['Heatsink','A structure that spreads heat and increases the area available for heat transfer.'],['Thermal interface material','Material between contacting surfaces that reduces the effect of microscopic air gaps.'],['Throttling','Reducing performance to remain within limits such as temperature or power.'],['Radiator','A heat exchanger that transfers heat from coolant to air.']],
steps:[['Follow the heat','A processor produces heat while operating. The cooler must make proper contact through the specified thermal interface. A heatsink spreads that heat, and airflow carries it away. Adding fans cannot compensate for a badly mounted cooler.'],['Choose compatible cooling','Check socket mounting, component clearance, case dimensions, and cooling requirements. Air coolers use heatsinks and often fans. Liquid systems add coolant, a pump, and a radiator; they still need airflow. Liquid cooling is not automatically necessary or better for every workload.'],['Inspect safely','Power down, disconnect power, and follow the service manual before internal work. Check blocked vents, dust, obstructed fans, mounting, and cable placement. Follow cleaning instructions and prevent uncontrolled fan spinning during cleaning. Never open the power-supply enclosure to clean its internals.'],['Replace interface material correctly','Follow the cooler and component instructions for preparation and application. Too much paste is not a substitute for correct contact. Remove protective film if the new cooler requires it. Some products use pre-applied material; do not assume every installation needs extra paste.'],['Verify under a suitable workload','After reassembly, confirm expected fan or pump operation and monitor temperature under a controlled representative workload. Compare against the component manufacturer’s limits rather than one universal temperature. If temperatures are acceptable but shutdowns continue, investigate other causes such as power or hardware faults.']],
lab:{task:'Paper lab: a recently replaced CPU cooler has a spinning fan, but temperature rises rapidly under load. Name two installation checks and explain why disabling throttling is inappropriate.',answer:'Check correct mounting/contact and whether the required thermal interface and protective-film removal were handled properly. Follow the service procedure with power disconnected. Throttling protects the component; disabling it does not correct poor heat transfer and can increase risk.'},
confusion:'A fan moving does not prove the heatsink is transferring heat effectively. High temperature is evidence to investigate, not proof every shutdown has the same cause.',
summary:['Follow heat from component to outside air.','Fit, mounting, thermal interface, and airflow all matter.','Verify temperatures under load without bypassing protection.'],related:['cpu','power','no-power'],
checks:[['A new cooler’s fan runs but the CPU rapidly overheats. What deserves checking?','Cooler contact and installation','DNS MX records','Printer duplex settings','Poor contact or installation can interrupt heat transfer even with a running fan. DNS mail records and printer settings cannot correct cooler contact.'],['Which component moves coolant in a typical active liquid-cooling loop?','Pump','DIMM slot','Network switch','The pump circulates coolant. A DIMM slot holds memory, and a network switch forwards network traffic.'],['What is appropriate after repairing an overheating problem?','Monitor under a controlled workload against vendor guidance','Disable thermal protection permanently','Assume fan noise proves the repair','Workload testing provides evidence that cooling is adequate. Disabling protection increases risk, and sound alone does not establish heat transfer.']],
tip:'Check the entire heat path; never treat thermal protection as the fault to remove.'
},
{
id:'expansion-cards',title:'Expansion cards: fit, lanes, power & drivers',domain:3,objective:'3.5',minutes:24,
big:'An expansion card must match the system electrically, physically, and in software—not merely fit an opening.',
taglish:'Kasya ang card does not mean compatible na. Check slot, available lanes, case clearance, power connectors, at driver support. Basahin ang motherboard manual bago bumili o magkabit.',
analogy:'A new appliance needs more than floor space: it also needs the right connection, enough power, and support for the job.',
exam:'Expansion cards include graphics, sound, network, and capture devices. PCI Express (PCIe) uses lanes. Slot length, electrical lane allocation, generation, shared resources, power, and firmware or operating-system support affect use.',
tech:'Before adding a graphics card, check dimensions, adjacent-slot clearance, supported power connections, total power capacity, and the motherboard’s slot configuration.',
flow:['Required function','Slot and clearance','Power and support','Install and test'],
goals:['Choose a card for a concrete requirement','Separate physical slot size from lane allocation','Plan safe installation and functional verification'],
terms:[['PCIe lane','A serial communication path used as part of a PCI Express connection.'],['GPU','Graphics processing unit: a processor used for graphics and other supported parallel workloads.'],['NIC','Network interface card: provides a network connection.'],['Capture card','A device that receives supported external audio/video signals for capture.']],
steps:[['Start with the task','A NIC adds network connectivity, a sound card adds supported audio functions, and a capture card receives video from another source. A graphics card generates display output. More hardware is useful only when it addresses the actual requirement.'],['Read the slot specification','A slot with x16 physical length may have fewer electrical lanes. Check the manual for supported cards and shared resources; using another slot or storage connector may change available bandwidth. Compatible PCIe generations can often negotiate a common link rate, but verify the entire platform and device support.'],['Budget physical space and power','Measure length, height, and thickness, including adjacent-slot use and cooling clearance. Check auxiliary power requirements and supported cables. CPU and graphics power connectors are not interchangeable merely because they look similar. Never assume modular PSU cables from another unit have compatible pinouts.'],['Install using the service procedure','Shut down, disconnect power, use appropriate electrostatic-discharge precautions, and secure the card without forcing it. Connect required power and external cables. Install a trusted driver supported by the operating system and device. Follow firmware guidance if configuration is required.'],['Test the intended feature','For a NIC, test link, addressing, and required network access. For graphics, test the intended display output and workload. For capture, confirm a supported input signal and application configuration. Seeing the card listed in the OS does not prove all its functions work.']],
lab:{task:'Paper lab: an x16-length slot is wired for x4, and a large graphics card would block the next slot. List three checks before approving the installation.',answer:'Check whether the card is supported with the available electrical lanes and expected workload, confirm physical clearance and effects on adjacent devices, and verify power capacity plus compatible power cables. Also confirm driver and firmware support before installation.'},
confusion:'Physical x16 length does not guarantee x16 electrical bandwidth. A capture input is not automatically a graphics output.',
summary:['Choose the required function first.','Confirm physical fit, electrical support, power, and software.','Test the actual feature after installation.'],related:['motherboard','power','display-diagnosis'],
checks:[['What adds a wired network connection to a supported desktop?','Ethernet NIC','Video capture card','Sound card','A network interface card provides network connectivity. Capture cards receive video; sound cards handle audio.'],['An x16-length slot is documented as x4 electrical. What is available?','Four electrical lanes','Sixteen lanes solely because of its length','No possible connection under any conditions','The documentation specifies four lanes. Physical length does not guarantee sixteen, and a compatible card may operate using the available link.'],['A graphics card appears in the OS. What further verification is useful?','Test its intended display output and workload','Assume every function has passed','Replace the DHCP server','Detection is only part of verification. Actual output and workload tests check the requested function; DHCP replacement is unrelated to local graphics verification.']],
tip:'Function → fit → lanes → power → driver → actual workload.'
},
{
id:'usb-docks',title:'USB-C and docks: check the whole connection',domain:1,objective:'1.2 / 3.2',minutes:23,
big:'A connector’s shape does not tell you every supported data, display, or charging capability.',
taglish:'Parehong USB-C ang plugs, pero puwedeng magkaiba ang features. Check laptop port, dock, cable, at monitor together. Charging works does not prove working ang video path.',
analogy:'Two doors can have the same shape but lead to different facilities. A matching entrance does not guarantee every service inside.',
exam:'USB-C is a connector type. USB data standards describe capabilities separately. Display output and power delivery depend on supported device, port, accessory, and cable functions. Docks can combine power, display, networking, and peripherals.',
tech:'A laptop charges through a dock but the monitor remains blank. Confirm the selected display input and the laptop port’s supported video or dock technology before replacing the monitor.',
flow:['Host port','Compatible cable','Dock capabilities','Peripheral requirements'],
goals:['Separate connector shape from supported functions','Trace charging and display as different paths','Isolate a failing dock function'],
terms:[['USB-C','A reversible connector shape used by devices with varying supported features.'],['Power Delivery','A power-negotiation capability supported by compatible devices and cables.'],['Alternate Mode','A supported mode that can carry another protocol, such as DisplayPort, through USB-C.'],['Dock','An accessory combining supported connections for a host device.']],
steps:[['List the desired functions','Write down whether you need charging, external displays, storage, Ethernet, or audio. Then check the exact host-port and dock specifications. A connector fitting is only the first check; product families can include ports with different capabilities.'],['Check the cable too','Use a cable rated and supported for the required functions and power. A charging cable may not provide the data or video capability needed by the dock. Do not infer ratings from color or connector shape. Check the manufacturer’s specifications and cable markings where provided.'],['Understand the display path','Some docks use supported native display signaling, while others use USB graphics technology with additional software requirements. Identify the dock design rather than assuming all video requires the same mode. Verify monitor input, resolution, refresh requirements, and the host’s external-display limits.'],['Treat charging independently','Charging depends on the negotiated capability of the power source, dock, cable, and laptop. A laptop under heavy load may consume more power than a dock provides. A charging indication does not prove the connection can also carry video, nor that enough power is available for every workload.'],['Isolate one function at a time','Test the peripheral directly when supported, then test the dock with an approved known-good cable or host. Check power and required software or firmware through trusted vendor guidance. Avoid disconnecting active storage without ejecting it properly; verify the user’s full setup after the fix.']],
lab:{task:'Paper lab: a dock charges the laptop and its keyboard works, but an attached display is blank. Explain what those successes establish and name two targeted next checks.',answer:'Charging establishes a working power function, and keyboard input establishes some data connectivity. Neither proves the dock’s display path. Check the dock’s video technology against the host port and software support, and confirm the monitor input and supported cable/display configuration.'},
confusion:'USB-C, USB data speed, display capability, and charging power describe different properties. They are not interchangeable labels.',
summary:['Check the host, cable, dock, and peripheral together.','Power success does not prove display success.','Match troubleshooting to the failing function.'],related:['mobile','network-media','display-diagnosis'],
checks:[['A USB-C plug fits. What can you safely conclude?','The connector physically matches; functions still need checking','Every USB and display feature is supported','Maximum charging power is guaranteed','Physical fit does not establish all supported functions. Data, video, and power depend on the participating equipment and cable.'],['A dock charges a laptop but shows no video. What is relevant?','Host and dock display support plus the display path','DNS MX priority','Printer separation rollers','Display capabilities and connections target the failed function. DNS mail priorities and paper-feed components cannot establish a dock’s video path.'],['A laptop slowly loses charge during heavy use on a dock. What should be compared?','Delivered power and workload requirements','Only the wallpaper color','The mail server’s port','The load can exceed delivered power. Compare supported power ratings and workload; wallpaper and mail-service ports do not determine the dock’s power capability.']],
tip:'Same plug, potentially different functions. Verify every part of the path.'
}
];
