// Original lessons addressing selected gaps, not a claim of full objective coverage.
export const essentialLessons = [
 {
  id:'ipv6', title:'IPv6: read the address and test the right path', domain:2, objective:'2.6', minutes:24,
  big:'IPv6 provides 128-bit addressing and can operate alongside IPv4. Test the protocol the failing connection actually uses.',
  taglish:'Puwedeng may IPv4 at IPv6 ang isang laptop. Kapag working ang IPv4, hindi ibig sabihin okay na ang IPv6. Basahin ang address at route, then test the actual connection bago mag-disable ng protocol.',
  analogy:'A building can have two delivery entrances. A successful delivery through one entrance does not prove the other entrance is open.',
  exam:'Recognize hexadecimal IPv6 notation, prefix length, link-local addressing, loopback, and dual stack. An IPv6 link-local address is normal; it is not the IPv4 APIPA failure clue.',
  tech:'A website works over IPv4 but fails over IPv6. Compare the AAAA lookup, IPv6 addressing, default route, and upstream IPv6 path. Do not conclude that all DNS is broken or disable IPv6 as a substitute for diagnosis.',
  flow:['Name lookup: A / AAAA','Selected IP version','Matching route','Application connection'],
  goals:['Read and expand a compressed IPv6 address','Distinguish link-local, unique-local, and loopback addresses','Investigate IPv4 and IPv6 separately'],
  terms:[['Hexadecimal','Base-16 notation using 0–9 and a–f.'],['Prefix length','The number of leading bits identifying a network prefix, such as /64.'],['Dual stack','Running IPv4 and IPv6 on the same system.'],['Link-local','An address used on one local link, not forwarded beyond it by routers.'],['Unique local address','An IPv6 address intended for local communications rather than global internet routing.']],
  steps:[
   ['Read the notation','A full IPv6 address has eight 16-bit hexadecimal groups. Leading zeros inside a group may be removed. One consecutive run of zero groups can be replaced with ::, but use that compression only once in an address. Expand back to eight groups to check your work.'],
   ['Work an example','2001:db8:0:0:0:0:0:25 compresses to 2001:db8::25. The 2001:db8::/32 block is reserved for documentation, so this is a paper example, not a public address to assign. In a /64 example, the first four full groups identify the network prefix; /64 is not a requirement for every possible IPv6 link.'],
   ['Recognize address scope','::1 is loopback and :: is the unspecified address. Link-local addresses belong to fe80::/10 and support local-link operations. Unique local addresses use fc00::/7; locally assigned ones use fd00::/8 and are not intended for global internet routing. A host may have several IPv6 addresses at once.'],
   ['Separate normal configuration from failure','IPv6 link-local addresses are expected even on a working network. Their presence does not prove DHCP failure. A client needs appropriate addressing and routing for remote IPv6 access. Automatic configuration may involve router advertisements and Stateless Address Autoconfiguration (SLAAC), with DHCPv6 used depending on the network design. Default-router discovery uses router advertisements.'],
   ['Test each path','DNS A records supply IPv4 addresses; AAAA records supply IPv6 addresses. Compare the failing lookup and connection with an authorized working client. Record which IP version a test uses, its destination, and the result. A local-link success or a working IPv4 website does not verify remote IPv6 access.']
  ],
  lab:{task:'Paper lab: a laptop has fe80::1234 and an IPv4 lease. It reaches a website over IPv4 but fails when testing the website’s IPv6 address. Explain what is normal, what remains unproven, and two useful checks.',answer:'The link-local IPv6 address is normal and does not establish a DHCP failure. IPv4 success does not verify an IPv6 route to the remote site. Check whether the network is intended to provide IPv6 internet service, then inspect appropriate IPv6 addressing and the default route. Compare the AAAA answer and upstream path with a working client; do not use a documentation address as a real test destination.'},
  confusion:'IPv4 link-local self-assignment after a missing lease and normal IPv6 link-local operation are different situations.',
  summary:['IPv6 is 128 bits; use :: only once per address.','Link-local is normal and stays on the local link.','Test IPv4 and IPv6 separately when the evidence differs.'],
  related:['ipv4','dns','dhcp','no-internet'],
  checks:[
   ['A working laptop has an IPv6 address starting fe80::. What does that establish?','It has a link-local IPv6 address','The DHCP server has definitely failed','It can definitely reach all IPv6 internet sites','Link-local addressing is normal in IPv6. It does not establish DHCP failure or verify routing to remote internet destinations.'],
   ['Which is a valid compression of 2001:db8:0:0:0:0:0:25?','2001:db8::25','2001::db8::25','2001:db8:25','One :: expands to the omitted zero groups. Two :: markers make the omitted lengths ambiguous, and three groups without compression do not express the full address.'],
   ['A service works with IPv4 but fails with IPv6. What is the most useful next investigation?','Check its IPv6 address and route separately','Assume both paths work because IPv4 worked','Replace the keyboard before checking routes','Separate protocols can have different addressing and routing failures. IPv4 success does not validate IPv6, and a keyboard replacement does not target this network symptom.']
  ],
  tip:'An address is a clue; scope and a working route determine where it can communicate.'
 },
 {
  id:'display-types', title:'Displays: panels, pixels & touch input', domain:3, objective:'3.1', minutes:24,
  big:'Display technology, resolution, pixel density, refresh rate, and touch sensing describe different parts of the viewing experience.',
  taglish:'Resolution ang dami ng pixels; refresh rate ang updates bawat second. Digitizer naman ang nakakaramdam ng touch. Puwedeng malinaw ang image pero hindi gumagana ang touch, kaya separate ang checks.',
  analogy:'A mosaic’s tile count and tile size differ from how frequently someone replaces the picture. A touch sensor is a separate way to tell the system where you pointed.',
  exam:'Compare LCD panel types, OLED, Mini-LED, digitizers, and legacy inverters. Distinguish screen resolution, pixel density, refresh rate, and color gamut; one specification cannot describe them all.',
  tech:'A monitor produces a clear image but touch does not work after moving desks. Check the supported touch-data connection, device detection, and required driver. A video connection alone may not carry the touch input for that display.',
  flow:['Graphics output','Supported video link','Panel creates image','Separate touch input returns data'],
  goals:['Compare LCD and OLED without confusing the backlight','Interpret display specifications independently','Separate video faults from touch-input faults'],
  terms:[['LCD','Liquid crystal display: modulates light from a backlight.'],['OLED','Organic light-emitting diode: display elements emit their own light.'],['Digitizer','The sensing component that converts touch or pen input into digital information.'],['Pixel density','Pixels per unit of physical distance, commonly pixels per inch (PPI).'],['Color gamut','The range of colors a display can reproduce.']],
  steps:[
   ['Identify how light is produced','LCDs use a backlight. In-plane switching (IPS), twisted nematic (TN), and vertical alignment (VA) are LCD panel types. OLED emits light at the pixel level without a separate LCD backlight. Mini-LED commonly describes an LCD backlight using many small LEDs; it does not mean that the display is OLED.'],
   ['Compare tendencies, then check the model','IPS commonly offers wide viewing angles, VA commonly offers strong native contrast, and TN has historically emphasized response and cost tradeoffs. OLED offers strong black levels but persistent static content can contribute to burn-in. Actual performance varies with the model and settings; panel names alone do not guarantee perfect color or motion.'],
   ['Separate the numbers','Resolution is the pixel grid, such as 1920 × 1080. With the same resolution, a smaller screen has higher pixel density. Refresh rate in hertz is the number of screen refreshes per second; it is not pixel count or an assurance that an application generates that many distinct frames. Color gamut describes a range, while calibration and accuracy describe how colors are reproduced.'],
   ['Check the complete signal path','A requested resolution and refresh rate must be supported by the graphics output, cable or adapter, input port, and monitor. A monitor advertised for a high refresh rate may offer that mode only through certain inputs. Consult the specifications before replacing the panel or assuming every physically fitting cable supports the same mode.'],
   ['Isolate touch and backlight symptoms','The digitizer handles input even when integrated into the same display assembly. A visible image with missing touch calls for checking the input path and device configuration. Some older LCDs used a cold-cathode fluorescent lamp (CCFL) and inverter; that legacy backlight system should not be assumed in modern LED-backlit or OLED panels. Follow service instructions around display power circuitry.']
  ],
  lab:{task:'Paper lab: two displays both have 1920 × 1080 pixels; one is 24 inches and the other 27 inches. Both show a picture, but the touchscreen model loses touch after reconnecting only its HDMI cable. Compare density and identify a targeted touch check.',answer:'The smaller 24-inch display has higher pixel density because the same pixel grid occupies less physical space. Resolution alone does not establish refresh rate or color accuracy. For the touch failure, check the manufacturer’s required touch-data connection, often a separate USB link, and device detection. The working HDMI picture does not prove that the digitizer data reaches the computer.'},
  confusion:'Mini-LED describes backlighting in this context. OLED is self-emissive. A digitizer senses input rather than generating the visible image.',
  summary:['Panel type and backlight technology are distinct concepts.','Resolution, density, refresh rate, and gamut measure different things.','For working video with failed touch, check the input path.'],
  related:['display-diagnosis','motherboard'],
  checks:[
   ['Which description best matches an OLED display?','Its display elements emit their own light','It requires a CCFL inverter to illuminate every image','It is another name for a USB digitizer','OLED is self-emissive. A CCFL inverter belongs to certain legacy LCD backlights, while a digitizer senses input rather than creating the visible image.'],
   ['Two screens have the same resolution but different physical sizes. Which has higher pixel density?','The smaller screen','The larger screen in every case','Both must have identical density','The same number of pixels occupies less physical space on the smaller screen. Density includes physical size, so equal resolution does not guarantee equal pixels per inch.'],
   ['A touch monitor shows video but stopped accepting touch after its USB cable was removed. What first?','Restore the required touch-data link','Replace the working video panel immediately','Change the DNS resolver','The disconnected USB input path directly fits the evidence. A working picture does not prove touch connectivity; panel replacement and DNS changes do not target the disconnected link.']
  ],
  tip:'Image output and touch input can fail independently.'
 },
 {
  id:'mobile-diagnosis', title:'Mobile faults: charging, heat & failed accessories', domain:5, objective:'5.4', minutes:25,
  big:'Mobile troubleshooting starts with the exact symptom, safe handling, and a comparison that changes one variable at a time.',
  taglish:'Hindi lahat ng ayaw mag-charge ay sirang battery. Check cable, charger compatibility, port, at temperature. Kapag may swelling o liquid warning, safety muna; huwag pilitin ang charging.',
  analogy:'A delivery can fail because of the road, the vehicle, or the receiving door. Checking one part at a time is more useful than replacing the whole building.',
  exam:'Recognize charging and battery problems, overheating, damaged ports, connectivity failures, unresponsive touch, and physical damage. Distinguish a failed accessory from a device-wide fault.',
  tech:'A phone charges through one known-compatible charger and cable but not another pair. Compare the cable and adapter separately before diagnosing its battery. Stop ordinary charging tests if there is swelling, unusual heat, damage, or a liquid warning.',
  flow:['Identify symptom and hazards','Check external path','Compare one variable','Verify normal use'],
  goals:['Separate a charging-path fault from battery failure','Respond appropriately to heat or physical damage','Isolate touch, Bluetooth, and app-specific failures'],
  terms:[['Charging negotiation','A supported device and power source agreeing on a permitted power mode.'],['Battery health','An estimate of battery condition, distinct from its present charge percentage.'],['Pairing','Establishing a Bluetooth relationship between devices.'],['Digitizer','The component that senses touch or pen input.']],
  steps:[
   ['Ask what actually fails','Does the device show no power, charge slowly, lose charge quickly, or fail only with one accessory? Record recent changes and whether the symptom affects one app or the whole system. Confirm important data and backup options before disruptive actions. A factory reset is not an initial answer to every mobile complaint.'],
   ['Trace the external charging path','On a device safe to test, compare a known-compatible power adapter, cable, and source. A fitting USB-C plug does not establish power capability or cable health. Inspect externally for damage without inserting metal tools. Change one variable at a time so a successful comparison identifies the useful difference.'],
   ['Separate charge level, health, and load','A full battery percentage describes current charge, not original capacity or expected runtime. Review battery-use information, screen brightness, background activity, and poor-signal conditions that can increase power use. Compare the same workload before and after a targeted change instead of declaring the battery failed from one short session.'],
   ['Handle physical warning signs','Stop using or charging a device with a swollen battery and arrange qualified service. Do not puncture it or force the case shut. For a liquid-detection warning, disconnect the cable and follow the manufacturer’s drying and service guidance; do not bypass the warning, apply external heat, or insert objects into the port. Move an overheating device out of direct sun and allow normal cooling; persistent abnormal heat needs service.'],
   ['Test the failing function','For Bluetooth audio, verify pairing mode, the selected output, volume, and whether another device already holds the connection. For one unresponsive app, compare another app before blaming the touchscreen. For touch failure across the system, consider the digitizer, connection, and device condition. Verify charging, audio, or touch during normal use after the repair, and document what changed.']
  ],
  lab:{task:'Paper lab: a tablet charges normally using adapter A and cable X. With adapter A and cable Y it repeatedly disconnects. There is no heat, swelling, or liquid warning. Name the strongest lead, a useful follow-up, and a conclusion that is premature.',answer:'Cable Y or its connection is the strongest lead because the adapter and tablet stayed the same. Inspect the cable and connector externally and compare with another supported cable, avoiding use of damaged accessories. A failed tablet battery is not established by these observations. After replacing the suspect cable, verify stable charging under comparable conditions and record the result.'},
  confusion:'Battery percentage, battery condition, and runtime under a particular workload are different measurements.',
  summary:['Check compatible power and accessories before replacing internal parts.','Physical hazards change the troubleshooting plan.','Compare one variable, then verify the function that failed.'],
  related:['laptop','mobile-sync','display-types'],
  checks:[
   ['The same tablet and adapter charge correctly with cable X but repeatedly disconnect with cable Y. What is the best lead?','Cable Y or its connection','A proven motherboard failure','A need to erase every app','The cable is the changed variable, so it is the most useful lead. The evidence does not prove motherboard failure, and erasing apps does not test that cable difference.'],
   ['A phone reports liquid in its charging connector. What is appropriate?','Disconnect the cable and follow manufacturer drying guidance','Force charging and ignore the warning','Insert a metal pin into the powered connector','Disconnecting and following the device guidance protects the connector. Bypassing the warning or probing with metal can cause damage and does not safely establish the cause.'],
   ['Touch fails inside one app but works elsewhere. What is the most useful first branch?','Investigate the affected app and its state','Assume the entire digitizer is broken','Replace the Wi-Fi access point','Working touch elsewhere narrows the symptom to the app or its state first. It does not prove total digitizer failure, and an access point replacement does not target local touch behavior.']
  ],
  tip:'Same device, same adapter, different cable: use that controlled comparison.'
 },
 {
  id:'wifi-diagnosis', title:'Slow Wi-Fi: signal, congestion & packet loss', domain:5, objective:'5.5 / 2.2', minutes:25,
  big:'A strong Wi-Fi indicator does not guarantee usable performance. Separate coverage, airtime contention, addressing, and upstream service.',
  taglish:'Full bars pero choppy ang call? Puwedeng busy ang channel o may packet loss. Compare near the access point, another client, at wired connection. Hindi speed test lang ang sagot.',
  analogy:'You can hear a speaker loudly but still struggle when many people talk at once. Signal strength and a clear opportunity to communicate are different.',
  exam:'Distinguish intermittent connectivity, interference, weak signal, latency, jitter, and packet loss. Use a Wi-Fi analyzer for nearby wireless channel information, while recognizing that it does not identify every non-Wi-Fi interferer.',
  tech:'Calls break up in one meeting room while wired users work normally. Compare a client near the access point and another client in the room. Inspect channel use and placement before treating the ISP as the established cause.',
  flow:['Scope the complaint','Compare local and wired paths','Inspect signal and channel use','Change one setting and retest'],
  goals:['Distinguish throughput, latency, jitter, and packet loss','Use comparisons to isolate wireless problems','Choose a targeted corrective action and verify it'],
  terms:[['Throughput','The rate of useful data actually delivered.'],['Latency','Communication delay, often measured as round-trip time in a test.'],['Jitter','Variation in packet delay, which can disturb real-time audio.'],['Packet loss','Packets failing to arrive at the measured destination.'],['Airtime','Time available for transmissions on a wireless channel.']],
  steps:[
   ['Turn slow into a measurable symptom','Ask whether files transfer slowly, calls stutter, or clients disconnect. Record location, time, affected devices, and the application. A large download can complete quickly while variable delay still disrupts a call. Test the complaint itself rather than treating a single download-speed number as the whole diagnosis.'],
   ['Compare coverage and contention','Distance and obstacles can weaken the signal. Nearby networks and active clients can also compete for airtime even when signal strength is good. Compare near the access point and at the failing location. Use an analyzer to inspect visible networks and channels; identifying every source of radio interference may require other equipment.'],
   ['Choose a compatible channel plan','Band, width, local regulations, and client support constrain the choices. Wider channels can increase available capacity in suitable conditions but occupy more spectrum. For conventional 20 MHz 2.4 GHz use in the US, 1, 6, and 11 are common non-overlapping choices. Do not apply those numbers to every band or country. A 6 GHz network also needs compatible clients.'],
   ['Separate local radio from upstream problems','Compare another client, a wired path, and an appropriate local service. If the local wireless path performs poorly while comparable wired access works, inspect radio conditions and the client. If wired and wireless both fail remotely, inspect shared routing and upstream services. Ping can provide delay and loss evidence, but filtering or prioritization can affect its results.'],
   ['Make one justified change','Adjust placement or an authorized channel setting based on the observations. Retest at the original location under similar load, watching connection stability and the application’s behavior. Check that other users still work. Document the change and a rollback option; replacing the router or increasing channel width without evidence can leave the cause unresolved.']
  ],
  lab:{task:'Paper lab: two clients have strong signal in a meeting room, but voice calls stutter at busy times. Wired calls remain clear. Explain why signal bars are insufficient, list two checks, and define success after a change.',answer:'Strong received signal does not prove that airtime is available or that delay and packet loss are acceptable. Inspect channel use and client activity, then compare delay variation and the call near the access point and in the room under similar load. After a justified change, repeat the original call conditions and check stability for both clients and other users. Wired success narrows the investigation but does not name one failed component.'},
  confusion:'High throughput is not the same as low latency. Strong signal is not the same as a quiet channel.',
  summary:['Measure the actual symptom and compare clients, locations, and paths.','Signal, interference, and airtime contention can have different remedies.','Verify the original workload after one justified change.'],
  related:['wifi','network-tools','no-internet','internet-types'],
  checks:[
   ['A video call stutters despite strong Wi-Fi signal. What remains possible?','Airtime contention or variable delay','Strong signal guarantees a clear call','The monitor resolution proves an ISP outage','Strong signal does not eliminate contention, jitter, or packet loss. It cannot guarantee application performance, and display resolution does not establish an ISP fault.'],
   ['Which tool helps inspect nearby Wi-Fi networks and channel use?','Wi-Fi analyzer','Punchdown tool','Disk cloning utility','A Wi-Fi analyzer provides wireless observations. A punchdown tool terminates conductors, and a disk cloning utility copies storage rather than surveying radio channels.'],
   ['An administrator changes the access point channel to address intermittent calls. What should follow?','Retest the original calls under comparable conditions','Declare success because the setting saved','Change several unrelated settings before testing','A saved setting is not proof of a resolved symptom. Retesting the original workload provides evidence; more simultaneous changes obscure which action helped or caused problems.']
  ],
  tip:'Strong signal + bad calls: investigate airtime, delay variation, and loss.'
 }
];
