// Original scenarios, not copied exam questions.
export const extendedLessons = [
 {
  id:'containers-vdi',title:'Containers & VDI: what runs where?',domain:4,objective:'4.1',minutes:25,
  big:'A virtual machine provides a guest operating system, a container packages an application environment, and VDI delivers a centrally hosted desktop session.',
  taglish:'Tanungin muna: saan tumatakbo ang app o desktop? VM has a guest OS. A typical container shares a host kernel. Sa VDI, remote ang desktop; hindi ibig sabihin na nasa laptop mo lahat ng processing.',
  analogy:'A VM is like a separate apartment, a container like a managed workspace sharing building facilities, and VDI like using a workstation through a remote window. Each analogy simplifies the actual isolation.',
  exam:'Compare VM guests, containers, and virtual desktop infrastructure by operating-system isolation, application requirements, and where the desktop executes. Deployment details can change isolation and resource needs.',
  tech:'Before changing a remote desktop service, compare the endpoint network path, session connection, and one application inside the desktop. A slow remote session is not proof that the endpoint needs more RAM.',
  flow:['Client or host','Connection / runtime','Application or desktop','Verify the requested task'],
  goals:['Compare VMs and containers','Explain where a VDI desktop executes','Isolate a remote-desktop symptom'],
  terms:[['Container','An application environment typically sharing the host kernel through OS-level isolation.'],['VDI','Virtual desktop infrastructure: centrally hosted desktops accessed from client endpoints.'],['Endpoint','The local device used to access the remote desktop or application.']],
  steps:[['Choose the required boundary','A VM runs a guest OS on virtual hardware. A typical container shares a kernel and packages an application with its dependencies. Host and workload compatibility still matter; packaging an application does not let any OS binary run anywhere.'],['Verify isolation requirements','Container isolation differs from giving each workload a full guest OS. Some platforms also offer VM-backed container isolation. Check the actual implementation and security requirements instead of assuming that every container is a small VM.'],['Locate the desktop','With VDI, the user interacts with a centrally hosted desktop through an endpoint. The endpoint still needs suitable client software and network connectivity. A remote desktop connection is a delivery path, not evidence that the remote computer is necessarily virtual.'],['Troubleshoot by scope','If only one application inside a responsive desktop is slow, investigate that application and its dependencies. If multiple users have session delay, compare shared infrastructure and network conditions. Avoid changing the endpoint hardware before measuring where the delay occurs.']],
  lab:{task:'Paper lab: a VDI desktop responds normally except for one database application. The same application is slow for several users, while their other desktop apps work. Identify a focused next investigation and one conclusion the evidence does not support.',answer:'Investigate the affected application and its shared backend or service path, comparing evidence from the users and service logs available to support staff. Responsive unrelated applications make a universal endpoint-input failure less likely. The evidence does not justify replacing every user’s laptop RAM or declaring the entire VDI platform broken.'},
  confusion:'Remote desktop is not automatically VDI, and a container is not automatically a complete guest operating system.',
  summary:['VMs and typical containers use different OS boundaries.','VDI hosts desktops centrally for endpoint access.','Locate the failing function before changing resources.'],related:['vm','cloud','no-internet'],
  checks:[
   ['A workload needs a separate guest kernel for an OS test. Which is the most direct fit?','A compatible virtual machine','A typical shared-kernel container alone','A VDI connection file by itself','A VM supplies a separate guest OS environment. A typical shared-kernel container does not supply an independent guest kernel, and a connection file only describes access to a remote resource.'],
   ['Where does a centrally hosted VDI desktop run?','On the hosting infrastructure, accessed through an endpoint','Always entirely on the endpoint’s local disk','Inside the keyboard firmware','The desktop executes on the hosting infrastructure. The endpoint provides access and user interaction; neither a local disk nor keyboard firmware is the defining VDI execution location.'],
   ['Only one app is slow inside an otherwise responsive remote desktop. What is the best initial scope?','The application and its dependencies','Replace every endpoint display cable','Assume the whole network is down','The symptom is specific to the application. Its dependencies are a focused investigation, while display cables and a total network outage do not fit an otherwise responsive remote desktop.']
  ],tip:'Identify the execution location, OS boundary, and failing function separately.'
 },
 {
  id:'mobile-management',title:'Managed mobile devices: policy, privacy & access',domain:1,objective:'1.3',minutes:24,
  big:'Mobile device management applies organizational settings and policies; personal connectivity alone does not prove access to a managed work application.',
  taglish:'May internet ang phone pero ayaw ng work app? Check account, enrollment, at compliance message. Huwag tanggalin ang management profile para lang mawala ang error; may company access at data na involved.',
  analogy:'A building visitor can reach the front door but still needs the correct badge and permission for a restricted office.',
  exam:'MDM supports device configuration, policy enforcement, and corporate applications. Corporate-owned and bring-your-own-device arrangements can have different management scope. Location services can use several sources rather than GPS alone.',
  tech:'Read the exact access or compliance error, confirm the intended account and enrollment, and follow the organization’s support process. Avoid assuming every failed work sign-in is a Wi-Fi fault.',
  flow:['Connectivity','Account and enrollment','Policy / app access','Verify approved function'],
  goals:['Separate connectivity from managed access','Explain corporate-owned and BYOD scope','Choose a policy-aware support response'],
  terms:[['MDM','Mobile device management: administration of supported device settings and policy.'],['BYOD','Bring your own device: personal hardware used for approved organizational work.'],['Compliance','Meeting the requirements defined by the organization’s management policy.'],['Location permission','An app’s allowed access to device location services.']],
  steps:[['Identify ownership and scope','Ask whether the device is organization-owned or personal and which management arrangement is intended. Management capability depends on the platform, enrollment mode, and policy. Do not assume a personal device has the same controls or visibility as a fully managed corporate device.'],['Read the access condition','An app may require the correct work identity and a compliant enrolled device. Working web browsing only proves some connectivity. Record the exact error and check the supported enrollment and app configuration before changing unrelated network settings.'],['Protect work and personal data','Follow the approved remediation or escalation path. Removing management or resetting a phone can affect work access and data. Explain the specific impact of an authorized action before performing it; do not use policy removal as a generic workaround.'],['Check location at the correct layer','Location estimates can use GPS, Wi-Fi, and cellular information depending on the device. If one app lacks location while another works, compare app permissions and organizational restrictions. A missing map location is not by itself proof of failed satellite hardware.']],
  lab:{task:'Paper lab: a personal phone browses websites normally, but a work app reports “device not compliant.” A colleague proposes deleting its management profile. Give a focused response that preserves both diagnosis and data.',answer:'Record the compliance message and confirm the intended work account and supported enrollment arrangement. Check the organization’s stated unmet requirement or escalate to its device-management support team. Deleting the profile can remove managed access or data and does not address the underlying requirement; do not treat it as routine connectivity repair.'},
  confusion:'Internet access is not equivalent to authorization. BYOD does not mean every device or app is automatically permitted.',
  summary:['Identify ownership and management scope.','Separate connection, identity, and compliance.','Use approved remediation and preserve data.'],related:['mobile','mobile-sync','mobile-diagnosis'],
  checks:[
   ['Browsing works but a work app reports a device compliance failure. What is the best next step?','Inspect the stated policy requirement and enrollment','Replace the access point immediately','Delete the management profile without checking impact','The message identifies a management requirement worth investigating. A working browser does not prove compliance; replacing the AP is unsupported and removing management can disrupt work access or data.'],
   ['What does BYOD describe?','Use of personal devices for approved organizational work','A guarantee that every app is authorized','A requirement to disable all management','BYOD describes an ownership/use arrangement. Organization policy still determines permitted access and management; it neither authorizes every application nor requires management to be disabled.'],
   ['One mapping app cannot access location but another can. What should be compared first?','App location permissions and applicable policy','Replace the GPS hardware immediately','Change printer paper settings','App-specific permissions or restrictions fit the differing behavior. Working location in another app argues against assuming a universal hardware failure, and printer media has no role in location access.']
  ],tip:'Connected → identified → enrolled as required → compliant → authorized.'
 }
].map(l=>({...l,question:l.checks[0][0],options:l.checks[0].slice(1,4),explanation:l.checks[0][4]}));
