import {componentLessons} from './component-lessons.js';
import {essentialLessons} from './essential-lessons.js';
import {serviceLessons} from './service-lessons.js';
import {practicalLessons} from './practical-lessons.js';
// Original guided lessons. Each mapping covers selected concepts within an objective.
export const guidedLessons = [
 {
 id:'mobile-sync',title:'Mobile accounts, pairing & synchronization',domain:1,objective:'1.3',minutes:20,
 big:'Mobile support means separating the connection, the account, and the data being synchronized.',
 taglish:'Connected sa Wi-Fi does not mean naka-sync na ang contacts. Check muna kung tamang account, enabled ang sync, at may permission ang app. Huwag agad mag-delete ng account: baka may unsynced data.',
 analogy:'A delivery van needs a working road, the correct destination, and permission to enter the building. A working road alone does not complete delivery.',
 exam:'Bluetooth pairing establishes a relationship with an accessory. Synchronization keeps selected data aligned across devices and services. Mobile device management (MDM) can enforce organizational settings; bring your own device (BYOD) describes personally owned equipment used for work.',
 tech:'A user receives new email but has no work contacts. Verify the selected account and contact-sync setting, then permissions and company policy. Check the service through its approved web interface to distinguish missing server data from a local sync failure.',
 flow:['Connection','Account and policy','Selected data','Verify sync'],
 goals:['Distinguish pairing from synchronization','Isolate account-specific sync failures','Explain MDM and BYOD'],
 terms:[['Pairing','Establishing a trusted Bluetooth relationship with an accessory.'],['MDM','Mobile device management: centralized configuration and policy enforcement.'],['Sync','Keeping selected data aligned; changes or deletions may propagate.']],
 steps:[['Establish the connection','For Bluetooth, enable the radios, put the accessory into pairing mode, select the correct device, confirm any displayed code, then test the intended function. An accessory may already be connected to another device.'],['Check identity and scope','Confirm the intended work or personal account. Email, calendar, and contacts can have separate sync controls. Check credentials, permissions, storage, and background-data restrictions without collecting the user’s password.'],['Check policy and cost','Managed devices may restrict apps or accounts. Respect policy and escalate restrictions to the administrator. Large initial syncs can consume a cellular data allowance; use an approved connection.'],['Verify carefully','Create an approved test item and verify it at both ends. Preserve unsynchronized information before removing accounts or resetting a device. Synchronization is not an independent backup.']],
 lab:{task:'Paper lab: work email updates, work contacts do not, and personal contacts are visible. Write two targeted checks and one action to avoid.',answer:'Check the work account’s contact-sync setting and the contacts app’s account filter or permission. Check managed policy if these are enforced. Avoid removing the account before preserving unsynchronized contacts.'},
 confusion:'GPS obtains positioning information; it does not itself provide internet access. Bluetooth pairing does not synchronize every application automatically.',
 checks:[['Email syncs but work contacts do not. What should you check first?','Contact sync and account selection','Replace the wireless card','Factory-reset immediately','The account’s contact settings directly match the symptom. Working email makes a complete radio failure less likely. A reset is disruptive and unsupported before targeted checks.'],['A managed phone blocks an unapproved mail app. What is appropriate?','Use the approved app or contact the MDM administrator','Bypass the management profile','Replace the SIM to remove policy','MDM can enforce application policy. Follow the approved workflow; bypassing management is inappropriate, and replacing a SIM does not remove device-management rules.'],['What is a risk of treating sync as a backup?','Deletions can synchronize to other devices','Sync always disables Wi-Fi','Pairing permanently erases the server','Synchronization can propagate deletion or unwanted changes. It does not inherently disable Wi-Fi, and Bluetooth pairing does not erase a server.']],
 tip:'Connection works? Next isolate the account, selected data, permission, and policy.'
 },
 {
 id:'vlan-vpn',title:'VLANs & VPNs: separation and remote access',domain:2,objective:'2.4',minutes:20,
 big:'A VLAN separates local network traffic logically. A VPN creates a protected connection across another network.',
 taglish:'VLAN parang magkahiwalay na departments kahit iisang building. VPN parang protected passage papunta sa office network. Magkaiba ang purpose nila; VLAN alone does not encrypt traffic.',
 analogy:'Separate rooms control where people gather. A protected passage connects someone outside the building to an approved destination.',
 exam:'A virtual local area network (VLAN) creates a logical broadcast domain. Communication between VLANs requires routing and is subject to access rules. A virtual private network (VPN) provides a logical tunnel; common remote-access implementations encrypt traffic across an untrusted network.',
 tech:'After a desk move, a client gets an address from the guest network and cannot reach a staff application. Compare the assigned switch-port VLAN with the documented staff configuration before changing DNS.',
 flow:['Client','Assigned VLAN','Router and access rules','Destination'],
 goals:['Choose VLAN or VPN for a requirement','Explain why routing is needed between VLANs','Diagnose a wrong-network assignment'],
 terms:[['Broadcast domain','Devices that receive the same Layer 2 broadcast traffic.'],['VLAN','A logical LAN segment on supporting network equipment.'],['VPN','A logical tunnel for connectivity across another network.']],
 steps:[['Separate local groups','A managed switch can place staff and guests into different VLANs even when they share physical equipment. A VLAN is a logical boundary, not a second wireless frequency.'],['Provide controlled paths','Different VLANs normally use different IP subnets. A router or Layer 3 switch provides inter-VLAN routing; firewall or access rules decide which communication is allowed. Separation is not encryption.'],['Connect remote users','A remote-access VPN authenticates a user or device and establishes a tunnel to an organization. Access still depends on authorization, routes, and name resolution. Some configurations tunnel all traffic; split tunneling carries only selected traffic.'],['Troubleshoot the correct boundary','Record the client address and network assignment. For local moves, compare VLAN configuration. For VPN problems, separate tunnel establishment from access to an individual resource. Do not remove access controls as a general fix.']],
 lab:{task:'Paper lab: choose the feature for (A) separating guest and staff devices on shared switches and (B) connecting an authorized employee from home. Does either choice automatically grant access to every server?',answer:'A: VLANs, with routing and access rules for permitted communication. B: a remote-access VPN. Neither grants universal access; authorization and network rules still apply.'},
 confusion:'A VLAN is not a VPN. Being connected to a VPN does not prove the internal DNS service or application is reachable.',
 checks:[['Guests and staff share managed switches but need separate broadcast domains. Choose the feature.','VLANs','More monitor ports','A larger DHCP lease time','VLANs create logical broadcast domains. Monitor ports are unrelated, and lease duration changes address lifetime rather than network separation.'],['A remote employee needs an approved protected path into the office. Choose the service.','Remote-access VPN','An unmanaged USB hub','A local printer queue','A VPN supports remote connectivity across another network. A USB hub adds local peripheral connections; a printer queue organizes jobs.'],['A moved PC receives a guest address instead of a staff address. Check what first?','Switch-port VLAN assignment','Display resolution','Replace the mail server','The move and wrong subnet point to network assignment. Display resolution cannot select a subnet, and replacing the mail server does not correct the local port configuration.']],
 tip:'VLAN: local separation. VPN: tunnel across another network. Access rules still matter.'
 },
 {
 id:'raid',title:'RAID: capacity, availability & backup',domain:3,objective:'3.4',minutes:22,
 big:'RAID combines drives to change performance or fault tolerance, but it does not replace an independent backup.',
 taglish:'RAID can keep work going kapag may drive failure, depende sa level. Pero kapag na-delete ang file, hindi automatic na maibabalik ng RAID. Kailangan pa rin ng separate backup.',
 analogy:'Having a second engine can help a vehicle continue after one fails. It does not undo taking the wrong road.',
 exam:'RAID 0 stripes without redundancy; RAID 1 mirrors; RAID 5 uses distributed single parity; RAID 6 uses dual parity; RAID 10 stripes across mirrored pairs. Capacity examples here assume equal-size drives and conventional layouts, before formatting and metadata overhead.',
 tech:'An array reports a failed drive but files remain accessible. Confirm backups and the controller’s exact drive identification. Follow the vendor replacement procedure; pulling the wrong member can cause data loss.',
 flow:['Choose level','Check capacity','Plan failure recovery','Maintain backup'],
 goals:['Compare RAID 0, 1, 5, 6, and 10','Calculate simple usable capacities','Explain the risk of a degraded array'],
 terms:[['Striping','Distributing data blocks across drives.'],['Mirroring','Keeping matching copies on separate members.'],['Parity','Redundant information used to reconstruct missing data.'],['Degraded','Operating with lost redundancy after a member failure.']],
 steps:[['Start with RAID 0 and 1','RAID 0 needs at least two drives, uses their combined capacity, and cannot tolerate any member failure. A conventional two-drive RAID 1 stores the same data on both members: two 2 TB drives provide about 2 TB usable capacity.'],['Compare parity arrays','RAID 5 needs at least three drives: usable capacity is (N − 1) × drive size, with tolerance for one failed member. RAID 6 needs at least four: (N − 2) × drive size, with tolerance for any two failed members.'],['Understand RAID 10','Conventional RAID 10 needs at least four drives in mirrored pairs and provides half the raw capacity. Multiple failures may be tolerated if no mirrored pair loses all its members. Any arbitrary two-drive failure is not guaranteed survivable.'],['Plan recovery','A rebuild reconstructs a replacement member and can reduce performance. Remaining failures during rebuilding can exceed tolerance. Confirm monitoring, compatible replacements, and tested backups; RAID does not protect against deletion, ransomware, theft, or every controller failure.']],
 lab:{task:'Paper lab: four 2 TB drives. Calculate conventional RAID 0, RAID 5, RAID 6, and RAID 10 usable capacity, excluding overhead. Which guarantees surviving any two member failures?',answer:'RAID 0: 8 TB. RAID 5: 6 TB. RAID 6: 4 TB. RAID 10: 4 TB. RAID 6 tolerates any two member failures; RAID 10 depends on which mirrored pairs are affected.'},
 confusion:'Fault tolerance maintains service through selected failures. Backup provides a separate recoverable copy, ideally with versions and isolation.',
 checks:[['Four 2 TB drives form RAID 5. What is nominal usable capacity before overhead?','6 TB','8 TB','2 TB','RAID 5 reserves the equivalent of one member for parity: (4 − 1) × 2 = 6 TB. 8 TB ignores parity; 2 TB is not this layout’s capacity.'],['Which listed level tolerates any two member failures?','RAID 6','RAID 0','RAID 5','RAID 6 has dual parity. RAID 0 has no redundancy, and RAID 5 tolerates only one member failure.'],['A user deletes a folder on a healthy mirrored array. What provides recovery?','A suitable independent backup or retained version','The mirror automatically undoes deletion','Replacing a healthy member','Deletion normally affects the logical array and its mirror. A retained recovery copy is needed; replacing healthy hardware does not undo the deletion.']],
 tip:'Memorize minimum drives and tolerance; always separate RAID from backup.'
 },
 {
 id:'cloud-deployment',title:'Cloud deployment, elasticity & availability',domain:4,objective:'4.2',minutes:20,
 big:'Cloud deployment describes who uses the environment; elasticity describes adjusting resources to demand.',
 taglish:'Public cloud does not mean public ang files mo. Shared ang provider infrastructure, pero may account permissions pa rin. Elasticity means puwedeng dagdagan at bawasan ang resources habang nagbabago ang demand.',
 analogy:'A shared office building can contain private locked offices. Booking more rooms during a busy season resembles scaling out, then releasing them resembles scaling back in.',
 exam:'Public, private, hybrid, and community describe deployment models. Infrastructure, platform, and software as a service describe service models. Resource pooling, rapid elasticity, measured service, and on-demand access are cloud characteristics.',
 tech:'A seasonal service needs extra capacity only during busy periods. Define scaling limits, monitor costs, and test behavior when a component fails. Paying for cloud resources does not automatically deliver an available application.',
 flow:['Demand changes','Allocate resources','Monitor service and cost','Release capacity'],
 goals:['Distinguish deployment from service models','Compare scaling and elasticity','Explain metering and availability'],
 terms:[['Hybrid cloud','A combination of distinct cloud environments connected to support their coordinated use.'],['Elasticity','Expanding and contracting capacity with changing demand.'],['Metered usage','Measuring consumption for visibility and often billing.'],['High availability','Designing to reduce service interruption when components fail.']],
 steps:[['Choose the deployment model','Public cloud serves multiple customers through a provider. Private cloud serves one organization and may be hosted on or off premises. Community cloud serves organizations with shared concerns. Hybrid connects distinct environments, such as private and public clouds.'],['Choose responsibility separately','A private environment can provide infrastructure services, while a public provider can provide finished software. Deployment and service model answer different questions: who uses the environment versus what the provider delivers and manages.'],['Match capacity to demand','Scaling up adds capacity to an instance; scaling out adds instances. Elastic systems can add and release resources with demand, often through automation. Set limits and verify the application can use additional capacity.'],['Design for failure and cost','Resource pooling does not mean unrestricted access to another customer’s data. Metered usage makes idle resources and data transfer worth monitoring. Availability needs suitable redundancy, health checks, and recovery design; backups address a separate recovery need.']],
 lab:{task:'Paper lab: one company runs a private cloud and integrates it with a public cloud for seasonal workloads. Classify the deployment. Explain what happens to resources after demand falls.',answer:'This is hybrid cloud. An elastic configuration can release capacity after the peak to match demand; resources do not necessarily disappear or stop billing unless configured or explicitly released.'},
 confusion:'Public cloud is not public data. Scalability is the ability to grow; elasticity includes contracting as demand falls.',
 checks:[['An organization integrates private and public clouds. Which deployment model applies?','Hybrid','SaaS','RAID 1','Hybrid describes connected cloud environments. SaaS is a service model; RAID 1 is a storage layout.'],['Demand drops and instances are released automatically. Which characteristic is shown?','Elasticity','A fixed CPU socket','Bluetooth pairing','Elasticity includes contracting resources as demand falls. CPU sockets and accessory pairing do not describe cloud resource allocation.'],['Does hosting an app in public cloud automatically make its stored data public?','No; access still depends on configuration and permissions','Yes; public means everyone can read it','Only if the app uses a keyboard','Public describes the deployment model, not an unconditional permission grant. Access controls remain necessary; keyboard use is unrelated.']],
 tip:'Deployment = environment. Service model = delivered capability. Elasticity = grow and shrink.'
 },
 {
 id:'display-diagnosis',title:'No display: isolate the signal path',domain:5,objective:'5.3',minutes:20,
 big:'A blank display can result from monitor power, input selection, cabling, the computer’s output, or a startup failure.',
 taglish:'May ilaw ang PC pero black screen? Hindi agad sira ang motherboard. Check monitor power, selected input, cable, at tamang output port. One change at a time para alam mo kung ano ang nakatulong.',
 analogy:'A television needs power, the correct input, a working cable, and a source sending a signal. Replacing the source before checking the input wastes effort.',
 exam:'Separate no power, no video signal, and failure to complete power-on self-test (POST). Resolution, refresh rate, cable capability, and input selection affect output. Built-in motherboard video outputs may require a processor with supported integrated graphics.',
 tech:'A desktop with a discrete graphics card was moved. The monitor says no signal. Verify the display input and that the cable is connected to the intended graphics output before opening the case.',
 flow:['Monitor power','Selected input','Cable and output','Startup evidence'],
 goals:['Follow the display signal path','Distinguish no signal from no power','Use one controlled substitution at a time'],
 terms:[['POST','Power-on self-test: startup hardware checks before normal operating-system loading.'],['Input source','The display’s selected connector, such as HDMI or DisplayPort.'],['Artifact','Unexpected visual distortion that requires isolating display, cable, or graphics causes.']],
 steps:[['Read the evidence','Check monitor power and its own on-screen menu. A visible menu indicates the panel can display something; it does not prove the cable or computer works. Record LEDs, messages, and startup sounds.'],['Trace the connection','Confirm the selected input matches the connected port. Inspect and reseat the external cable. Check adapter direction and supported functions; not every USB-C port provides video.'],['Compare known-good parts','Try a supported known-good cable or monitor, changing one item at a time. If the same monitor works with a second source, investigate the first computer’s output and configuration.'],['Escalate with startup clues','If there is no output on known-good displays, inspect documented POST indicators and recent hardware changes. Follow the service manual and power-disconnection precautions before internal work. Verify normal output after the repair and record the actual cause.']],
 lab:{task:'Paper lab: the monitor menu works, HDMI 2 is selected, and the cable is connected to HDMI 1. State the first action and the next check if that fails.',answer:'Select HDMI 1 and test. If there is still no signal, inspect the connection and use a supported known-good cable or source, changing one variable at a time. The menu is evidence of monitor power, not proof of a working source.'},
 confusion:'Spinning fans do not prove successful POST. A no-signal message is different from a completely unpowered monitor.',
 checks:[['The monitor is set to HDMI 2 but its cable uses HDMI 1. What first?','Select HDMI 1','Replace RAM immediately','Reinstall the operating system','The input mismatch directly explains the symptom. RAM replacement and OS reinstallation are unsupported before correcting the signal path.'],['Fans spin but no screen appears. What can you conclude?','Some power is present; successful POST is not proven','The operating system definitely loaded','The monitor cable definitely works','Fans show some power delivery, not successful startup. Neither OS loading nor cable operation is established by fan movement.'],['A screen works with another computer using the same cable. What next?','Investigate the original computer’s output and startup','Discard the working screen','Replace the network switch','The comparison shifts attention toward the original source. Discarding a working screen is unsupported, and a network switch does not provide the local video signal.']],
 tip:'Power → input → cable → output → startup evidence. Change one variable at a time.'
 }
].concat(practicalLessons,serviceLessons,essentialLessons,componentLessons).map(l=>({...l,question:l.checks[0][0],options:l.checks[0].slice(1,4),explanation:l.checks[0][4]}));

