// Original guided content mapped to selected Core 1 concepts.
export const serviceLessons = [
{
id:'host-services',title:'Network services: who does what?',domain:2,objective:'2.3',minutes:22,
big:'A server role describes a service offered to clients, not necessarily a separate physical machine.',
taglish:'Parang office departments: bawat service may trabaho. DNS finds records, DHCP gives network settings, at file server provides shared files. Puwedeng maraming roles sa isang machine, pero separate pa rin ang troubleshooting.',
analogy:'One office building can contain a directory desk, records department, and mailroom. Knowing which department failed makes the investigation more precise.',
exam:'Network hosts can provide name resolution, address assignment, file sharing, printing, mail, web content, databases, centralized logging, time synchronization, and authentication services. Identify the role from the requested function.',
tech:'A user can sign in but receives access denied on one shared folder. Compare permissions and group membership with the approved access request. Successful authentication does not automatically authorize every resource.',
flow:['Client request','Relevant service','Access decision','Response or log'],
goals:['Match common services to their roles','Separate authentication from authorization','Use logs and time to investigate incidents'],
terms:[['AAA','Authentication, authorization, and accounting: identity verification, permitted actions, and activity records.'],['Syslog','A mechanism used by many systems to send event messages to a logging service.'],['NTP','Network Time Protocol: synchronizes system clocks.'],['Database server','A service that stores and retrieves structured data for applications.']],
steps:[['Identify the requested service','DNS looks up records, while DHCP leases network configuration. A file server provides shared file access. A print server manages shared printing. A web server responds to web requests; a database server handles application data. These roles can run on physical hosts, virtual machines, or hosted services.'],['Separate identity and permission','Authentication asks who you are. Authorization decides what you may do. Accounting records activity. An accepted sign-in followed by access denied is a reason to check authorization, not proof the network cable has failed. Follow approved access procedures instead of granting broad privileges.'],['Correlate evidence','Centralized logs help compare events from several devices. Consistent time makes those records easier to line up and can be required by authentication systems. NTP synchronizes clocks; it does not collect the event messages that syslog handles. Check the actual time as well as the displayed time zone.'],['Trace dependencies','A web application can depend on DNS, authentication, and a database. A reachable web page with failed sign-in does not establish a database fault by itself. Record the failing operation, affected users, timestamps, and service responses before escalating to the responsible team.']],
lab:{task:'Paper lab: users can sign in and open shared files, but event timestamps differ between two servers. Identify the relevant service and explain why replacing the file server is premature.',answer:'Investigate clock synchronization and the configured time source, including NTP reachability and time-zone display. File access already works; inconsistent timestamps point to time configuration rather than evidence that the file service must be replaced.'},
confusion:'A role is not a chassis. One host can provide several roles, and one role can be distributed across several hosts.',
checks:[['Sign-in succeeds but a shared folder reports access denied. What should you investigate?','Authorization and folder permissions','Replace the monitor','Change every client IP address','Successful sign-in separates identity verification from the folder access decision. Permissions are relevant; monitor replacement and wholesale address changes do not address authorization.'],['Which service helps keep host clocks synchronized?','NTP','A print queue','DHCP reservations alone','NTP synchronizes clocks. Print queues manage jobs, and reserving an IP address alone does not synchronize time.'],['Which role centralizes event messages from supported network devices?','Syslog collector','File compression utility','Display calibration service','A syslog collector receives supported event messages. Compression changes file representation, while display calibration affects visual output.']],
tip:'Identity = authentication. Permission = authorization. Activity record = accounting.'
},
{
id:'internet-types',title:'Internet connections & network types',domain:2,objective:'2.7',minutes:22,
big:'Choose connectivity by availability, delay, throughput, reliability, and usage limits rather than the technology name alone.',
taglish:'Wi-Fi is the local wireless connection; hindi siya automatic na internet service. Puwedeng connected sa Wi-Fi pero down ang ISP. Compare latency, upload, download, coverage, at data limits sa actual location.',
analogy:'A driveway connects your house to a road, while the wider road system takes you to another town. A clear driveway does not prove the highway is open.',
exam:'Internet access can use fiber, cable, digital subscriber line (DSL), satellite, cellular, or a wireless internet service provider (WISP). LAN, WLAN, WAN, PAN, MAN, and SAN describe different network contexts.',
tech:'A remote office needs video calls and cloud backups. Compare measured latency, upload capacity, coverage, reliability, and usage limits. Confirm backup access does not share the same likely failure point as the primary service.',
flow:['Application needs','Local availability','Measured characteristics','Primary and backup plan'],
goals:['Compare common access technologies','Distinguish local Wi-Fi from internet service','Recognize common network-type acronyms'],
terms:[['LAN / WLAN','Local area network / wireless local area network: local connectivity, with WLAN using wireless links.'],['WAN / MAN','Wide area network / metropolitan area network: connections across broader geographic areas or a metropolitan region.'],['PAN','Personal area network: short-range connectivity around an individual, such as Bluetooth accessories.'],['SAN','Storage area network: a specialized network providing access to storage, commonly at block level.']],
steps:[['Separate access from the local link','A laptop can reach a local printer over Wi-Fi while the ISP connection is unavailable. The access point provides a local wireless link; the upstream service connects the site beyond its LAN. A combined home device may perform several roles in one enclosure.'],['Compare wired access','Fiber carries optical signals. Cable access commonly uses a cable modem on coaxial infrastructure. DSL uses telephone copper, and performance is affected by the line and distance to provider equipment. Actual plans and installations determine throughput and upload/download symmetry.'],['Compare wireless access','Cellular uses a carrier radio network; coverage, congestion, and usage limits matter. A WISP provides internet using wireless links, often to fixed premises. Satellite can serve remote sites, but latency differs substantially between orbital systems and service designs. Do not assume every satellite connection has the same delay.'],['Match the network to the job','A PAN connects nearby personal devices; a LAN or WLAN serves a local site. A WAN connects across wider areas, and a MAN spans a metropolitan area. A SAN serves storage access; it is not simply another name for any shared folder. Test the applications that matter instead of evaluating download speed alone.']],
lab:{task:'Paper lab: a laptop prints to a local Wi-Fi printer but cannot reach external websites. Explain what is established and name two useful next checks.',answer:'The local path to the printer works, but the upstream internet path and name resolution are not proven. Check gateway/upstream status and compare a known valid name lookup with reachability tests. Also determine whether other clients show the same issue.'},
confusion:'Bandwidth is capacity; latency is delay. A high-bandwidth connection can still have delay that affects interactive work.',
checks:[['A Bluetooth headset and phone form which network context?','PAN','SAN','MAN','A personal area network describes nearby personal devices. A SAN is specialized storage networking, while a MAN covers a metropolitan area.'],['Which metric is most directly about communication delay?','Latency','Storage capacity','Monitor resolution','Latency measures delay. Storage capacity measures data space, and monitor resolution measures the displayed pixel arrangement.'],['Local Wi-Fi printing works while all external services fail. What is justified?','Investigate the shared upstream path and related services','Assume Wi-Fi proves internet access','Replace every printer cartridge','A working local path does not prove upstream access. Check shared connectivity and relevant services; cartridges do not supply internet connectivity.']],
tip:'Local connection, internet access, bandwidth, and latency are separate things to verify.'
},
{
id:'storage-diagnosis',title:'Drive failure: protect data before testing',domain:5,objective:'5.2',minutes:24,
big:'Storage troubleshooting begins by protecting important data and separating detection, boot, performance, and array problems.',
taglish:'Kapag clicking ang HDD at may important files, huwag paulit-ulit na stress test. Alamin muna ang backup at recovery policy. Drive detected does not mean healthy, at missing boot device does not always mean dead ang drive.',
analogy:'If a filing cabinet is collapsing, protect the records before repeatedly opening and slamming the drawers to test the hinges.',
exam:'Storage symptoms include missing drives, boot-device errors, unusual mechanical noise, health warnings, slow reads or writes, data corruption, and RAID alerts. A single symptom is evidence to investigate, not a guaranteed diagnosis.',
tech:'A previously working computer reports no bootable device after maintenance. Check whether firmware detects the intended drive and whether boot configuration changed. Preserve data and avoid initializing or formatting a drive merely because it does not boot.',
flow:['Protect data','Determine scope','Targeted non-destructive checks','Recovery and verification'],
goals:['Separate drive detection from bootability','Recognize warning signs and data risks','Respond safely to a degraded RAID array'],
terms:[['S.M.A.R.T.','Self-Monitoring, Analysis and Reporting Technology: drive health reporting that may reveal developing problems.'],['Bootable device','A device with a suitable startup path and boot information for the system configuration.'],['IOPS','Input/output operations per second: a workload-dependent storage performance measure.'],['Degraded array','An array operating after a member failure with reduced redundancy.']],
steps:[['Protect the recovery options','Ask what data matters and verify backup availability. For severe symptoms such as abnormal mechanical noises with irreplaceable data, stop unnecessary use and follow professional recovery procedures. Repeated retries, repair writes, or stress tests may worsen a failing drive or reduce recovery options.'],['Separate detection from startup','If firmware cannot detect the drive, investigate power, connection, interface support, and hardware using the service procedure. If detected but not bootable, investigate the boot order, intended operating-system entry, and recent changes. Do not format or initialize a data-bearing drive as a diagnostic shortcut.'],['Interpret performance and health','Health warnings warrant attention, but a passing health status does not guarantee no failure. Slow performance may involve workload, limited free space, interface limits, heat, or device faults. Compare observations and supported diagnostics after the data-protection plan is established.'],['Handle arrays carefully','Confirm the controller’s exact failed-member identification and backup status. Replace only the identified member with a supported device using vendor instructions. Rebuilds take time and may affect performance. Do not remove another drive or create a new array over the existing data just to clear an alarm.']],
lab:{task:'Paper lab: firmware detects the original drive, but a boot error began after a new drive was installed. Propose a non-destructive first investigation and one action to avoid.',answer:'Compare the boot order and intended operating-system boot entry with the original configuration, while confirming backups and the detected drives. Avoid initializing or formatting the original drive; detection and a changed boot configuration do not establish that its data is unusable.'},
confusion:'A detected drive may still fail. A nonbooting drive may still contain recoverable files. RAID redundancy is not an independent backup.',
checks:[['A clicking HDD holds irreplaceable data with no known backup. What is the priority?','Stop unnecessary access and follow recovery policy','Run repeated write stress tests','Initialize the drive immediately','Protect recovery options and follow an appropriate recovery procedure. Repeated writes or initialization can worsen damage or overwrite important information.'],['A boot error starts after adding a second drive, while the original is detected. What should you check?','Boot order and intended boot entry','Printer paper size','Erase the original drive first','The installation may have changed the selected startup path. Paper settings are unrelated, and erasing the original data is not a justified first check.'],['One RAID member has failed. What should precede replacement?','Confirm exact member identity, backups, and vendor procedure','Remove a random drive to see what happens','Create a fresh array over the existing members','Precise identification and recovery preparation reduce the risk of losing the array. Random removal or recreating the array can destroy access to existing data.']],
tip:'Protect data first. Then distinguish not detected, not bootable, slow, and degraded.'
}
];
